'use client';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { AuthContextProvider } from './context/AuthContext';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] })
const metadata: Metadata = {
  title: 'Bakery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <AuthContextProvider>
                <Navigation />
                {children}
                <Footer />
            </AuthContextProvider>
        </body>
    </html>
  )
}
